# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1024, verbose_name='адрес')),
                ('license', models.CharField(max_length=128, verbose_name='лицензия')),
                ('square', models.FloatField(verbose_name='площадь')),
                ('historic', models.BooleanField(verbose_name='историческое значение')),
                ('latitude', models.FloatField(verbose_name='широта')),
                ('longitude', models.FloatField(verbose_name='долгота')),
            ],
            options={
                'verbose_name': 'строение',
                'verbose_name_plural': 'строения',
            },
        ),
    ]
